### ISSUE TITLE
DOI: make default option selection configurable

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#163]
The UI widget at the moment shows by default the text input where you insert your already pre-existing DOI.
We should change this and make it configurable, as in CDS most of the users will not have a DOI.

![Screenshot 2024-06-25 at 10 50 50](https://github.com/CERNDocumentServer/cds-rdm/assets/2089455/5bb1c904-a0c7-40e3-a057-e713f88fdb4f)

**Comment by sakshamarora1** [comment]
Summary of the discussions for optional DOI UI

## Backend:
1. The functionality already exists, can be configured by adding the following lines to the invenio.cfg file:
```
from invenio_rdm_records.config import RDM_PERSISTENT_IDENTIFIERS, RDM_PARENT_PERSISTENT_IDENTIFIERS
RDM_PERSISTENT_IDENTIFIERS["doi"]["required"] = False
RDM_PARENT_PERSISTENT_IDENTIFIERS["doi"]["required"] = False
``` 
2. Needs a bugfix on [this line](https://github.com/inveniosoftware/invenio-rdm-records/blob/e20bd904df73eb6c13ace9c671639a704c3199b7/invenio_rdm_records/resources/serializers/datacite/schema.py#L421) when required is false, it errors

## Frontend: 
1. To implement the following UI when required is set to false.
![Image](https://github.com/user-attachments/assets/8458efd4-916b-4b05-856c-557e20a100ee)
2. The `required=true` config flag will show 2 radio button, while `required=false` will show the 3rd one
3. When the user selects `No, I need one`, the user must click on `Get a DOI now` button , otherwise the validation should fail. (Draft save or publish)
4. Make the selection of the default radio button configurable. (explore the possibility to have a 4th option for none default that will force the user to select one of the options)

Discussion link: https://github.com/inveniosoftware/product-rdm/discussions/205
