### ISSUE TITLE
[SSPN][Migration] Beams field values

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-rdm#237]
Attached the list of values for the field `693__b` Beam field.

[beams.csv](https://github.com/user-attachments/files/17570729/beams.csv)

**Comment by PaulinaBaranowska** [comment]
Please assign this to me

**Comment by PaulinaBaranowska** [comment]
We have cleaned up the values in `693__b` that seemed out of place: [Beams values_corrected.xlsx](https://github.com/user-attachments/files/17776676/Beams.values_corrected.xlsx)
We consulted ATS, and it seems that a list of transfer lines can be extracted from the [Layout Database](https://layout.cern.ch/elements?navigator=MACHINE&version=EYETS%202024-2025). So the question is, should this be controlled vocabulary? From what we see in https://github.com/CERNDocumentServer/cds-rdm/pull/244 it might be planned as a freetext field?

Looking at the current displays you have, perhaps the phrasing under the individual fields should be changed from 
"You should fill this field with one of the recognised accelerators" to "Please select a recognised accelerator from the list _**if applicable**_" It might prevent people from submitting garbage because they think they need to put something in the field.

**Comment by ntarocco** [comment]
Thank you, we will see how to get the data. Related [issue](https://github.com/CERNDocumentServer/cds-rdm/issues/259).

**Comment by michamos** [comment]
[Comment I made on Mattermost](https://mattermost.web.cern.ch/it-dep/channels/new-cdslibrary-task-force/5argnkdj9jg5uqk5ak1ofwrwfh):
> Paulina was informed about the Layout DB by a user, we don't know who maintains the list of beam lines and if there's an independent source of info. Maybe we could start by simply having a controlled vocabulary that contains the list of values that are currently in use on CDS, then revisit it when we tackle the collections that are more relevant for the EN/BE departments?

**Comment by zzacharo** [comment]
> We have cleaned up the values in `693__b` that seemed out of place: [Beams values_corrected.xlsx](https://github.com/user-attachments/files/17776676/Beams.values_corrected.xlsx) We consulted ATS, and it seems that a list of transfer lines can be extracted from the [Layout Database](https://layout.cern.ch/elements?navigator=MACHINE&version=EYETS%202024-2025). So the question is, should this be controlled vocabulary? From what we see in #244 it might be planned as a freetext field?
> 
> Looking at the current displays you have, perhaps the phrasing under the individual fields should be changed from "You should fill this field with one of the recognised accelerators" to "Please select a recognised accelerator from the list _**if applicable**_" It might prevent people from submitting garbage because they think they need to put something in the field.

beams custom field was implemented as a dropdown field autocompleting from the list of curated values. We continue enriching the vocabulary for later collections in #259
