### ISSUE TITLE
migration: contributors - add full roles mapping

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-rdm#25]
- [ ] extract possible author roles from legacy
- [ ] update current roles mapping with missing values. If there are roles that are not quite matching the existing RDM roles, discuss with the team to consider adding additional roles to the vocabulary if needed.

**Comment by anikachurilova** [comment]
In SSPN collection, there are no records that have `100__e` field (contributor roles). Closing this ticket because of that. Here is a script to check this for the next collections if needed: https://gitlab.cern.ch/cds-team/production_scripts/-/blob/master/cds/collect_all_authors_roles.py?ref_type=heads
